spring:
  application:
    name: course-catalog-service
message: Hello from default profile
#
#---
#spring:
#  config:
#    activate:
#      on-profile: prod
#
#message: Hello from PROD profile
#
#---
#spring:
#  config:
#    activate:
#      on-profile: stg
#
#message: Hello from STG profile